### ISSUE TITLE
pca model different now?

### ISSUE THREAD

**Issue by luechtian** [jannikbuhr/ShinyLipids#57]
[pca_after_update.pdf](https://github.com/jannikbuhr/ShinyLipids/files/5057597/pca_after_update.pdf)
[pca_before_update.pdf](https://github.com/jannikbuhr/ShinyLipids/files/5057598/pca_before_update.pdf)

Areas of convex hull and loadings are quite different.

**Comment by jannikbuhr** [comment]
Yes, but the change difference you are seeing might just be from different settings (like centering and scaling). https://github.com/jannikbuhr/ShinyLipids/commit/bc1adc037b8e2a9877927516f3829a846b2e7068 unified the way default values for the interface are handled and now scaling is the default whereas it previously wasn't.
