### ISSUE TITLE
Lipid amounts in micromolar

### ISSUE THREAD

**Issue by ddkale** [jannikbuhr/ShinyLipids#62]
Hi Janik, this is not issue actually. I need for my data plots represented in uM , and not in mol %, Could you please help me how may I change the codes to get these plots in uM instead of mol%

**Comment by jmbuhr** [comment]
Simply don't standardize and the plot will be in μM. Keep in mind that if you then want to quantitatively compare samples you have to be sure that each sample and technical replicate thereof contains the same total amound of lipids.

![image](https://user-images.githubusercontent.com/17450586/220318339-a108f75c-35b0-4b21-b996-f9ee191eaad0.png)

**Comment by ddkale** [comment]
Many thanks Janik, best wishes Dipali
